apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onurglr/app-of-apps-argocd.git
    targetRevision: HEAD
    path: apps/manifests/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

